// 커뮤니티 화면에서 사용할 더미 데이터

export const mockPosts = [
  {
    id: 1,
    title: "정보처리기사 실기 합격 후기! 🎉",
    content: "드디어 합격했습니다! 이 플랫폼 덕분에 효율적으로 공부할 수 있었어요. 특히 AI 해설 기능이...",
    author: "합격왕",
    authorId: "user123",
    isAnonymous: false,
    category: "후기",
    likes: 42,
    comments: 15,
    views: 234,
    createdAt: "2시간 전",
    isPinned: true,
    isLiked: false,
  },
  {
    id: 2,
    title: "토익 문법 팁 공유합니다",
    content: "제가 토익 공부하면서 정리한 문법 팁 공유해요. 시제 파트가 제일 중요한데요...",
    author: "익명",
    authorId: "anonymous",
    isAnonymous: true,
    category: "꿀팁",
    likes: 28,
    comments: 8,
    views: 156,
    createdAt: "5시간 전",
    isPinned: false,
    isLiked: true,
  },
  {
    id: 3,
    title: "같이 스터디 하실 분 구해요!",
    content: "정보처리기사 준비하시는 분들 같이 스터디 하면 좋을 것 같아요. 주 3회 정도...",
    author: "스터디러버",
    authorId: "user456",
    isAnonymous: false,
    category: "스터디",
    likes: 19,
    comments: 12,
    views: 98,
    createdAt: "1일 전",
    isPinned: false,
    isLiked: false,
  },
  {
    id: 4,
    title: "배틀 모드 너무 재밌어요 ⚔️",
    content: "처음엔 긴장됐는데 하다보니 진짜 재밌네요! 실력도 늘고 경쟁심도 생기고...",
    author: "익명",
    authorId: "anonymous2",
    isAnonymous: true,
    category: "자유",
    likes: 35,
    comments: 6,
    views: 187,
    createdAt: "1일 전",
    isPinned: false,
    isLiked: false,
  },
  {
    id: 5,
    title: "약점 분석 기능 진짜 좋네요",
    content: "제가 어떤 부분이 약한지 바로 알 수 있어서 집중적으로 공부하기 좋아요!",
    author: "공부중독",
    authorId: "user789",
    isAnonymous: false,
    category: "후기",
    likes: 24,
    comments: 4,
    views: 142,
    createdAt: "2일 전",
    isPinned: false,
    isLiked: false,
  },
];

export const mockComments = [
  {
    id: 1,
    postId: 1,
    author: "축하해요123",
    authorId: "user999",
    isAnonymous: false,
    isAuthor: false,
    content: "축하드려요! 저도 곧 시험인데 힘이 나네요 💪",
    likes: 5,
    createdAt: "1시간 전",
    isLiked: false,
  },
  {
    id: 2,
    postId: 1,
    author: "합격왕",
    authorId: "user123",
    isAnonymous: false,
    isAuthor: true,
    content: "감사합니다! 여러분도 꼭 합격하세요 ✨",
    likes: 8,
    createdAt: "30분 전",
    isLiked: true,
  },
  {
    id: 3,
    postId: 1,
    author: "익명",
    authorId: "anonymous3",
    isAnonymous: true,
    isAuthor: false,
    content: "혹시 실기 준비 기간은 얼마나 하셨나요?",
    likes: 2,
    createdAt: "15분 전",
    isLiked: false,
  },
];
